### ISSUE TITLE
Epic: v8

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/frost#100]

**Comment by jackgavigan** [comment]
Suggestion: Expand the scope of this epic to include the v6/v7-related stuff (e.g. #91 & #92).

**Comment by dconnolly** [comment]
> Suggestion: Expand the scope of this epic to include the v6/v7-related stuff (e.g. #91 & #92).

These are in the #69 epic

**Comment by dconnolly** [comment]
🎉
