### ISSUE TITLE
Review and officially submit the Re-randomizable FROST ZIP

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost#119]

**Comment by mpguerra** [comment]
@conradoplg can I please get an estimate on this one?

**Comment by conradoplg** [comment]
@mpguerra I'm not sure what the scope we want for this ticket. Is addressing the comments after the submission be part of this, or should that be another ticket (and then this one is completed)?

**Comment by mpguerra** [comment]
So I think we are probably done with the "officially submit" part with https://github.com/zcash/zips/pull/662 

I'd be inclined to close this one as done for now and keep tracking the outstanding work in the ZIPs repo

**Comment by conradoplg** [comment]
Estimated to match the already done work (mostly updating to the most recent RFC draft) and closing as done with https://github.com/zcash/zips/pull/662 being opened
