### ISSUE TITLE
Update Re-randomizable FROST implementation to V11

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost#120]

**Comment by conradoplg** [comment]
I updated the implementation, updating https://github.com/ZcashFoundation/frost/pull/83 and https://github.com/ZcashFoundation/reddsa/pull/26.

Since those won't be merged as-is since they need https://github.com/ZcashFoundation/frost/issues/121, I'm thinking of closing this issue as done, without review, since the code will be reviewed in #121. @mpguerra what do you think?

**Comment by dconnolly** [comment]
> I updated the implementation, updating #83 and [ZcashFoundation/reddsa#26](https://github.com/ZcashFoundation/reddsa/pull/26).
> 
> Since those won't be merged as-is since they need #121, I'm thinking of closing this issue as done, without review, since the code will be reviewed in #121. @mpguerra what do you think?

I'm cool with this 👍

**Comment by conradoplg** [comment]
Closing per the rationale above
