### ISSUE TITLE
Use nonce_generate test vectors

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost#133]
New test vectors were added in https://github.com/cfrg/draft-irtf-cfrg-frost/pull/277

 - Update the test vectors
- Test `nonce_generate` with them

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/frost/133?planning-poker) with Zenhub @conradoplg @dconnolly
