### ISSUE TITLE
Implement hash to scalar functions?

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/frost#14]

**Comment by dconnolly** [comment]
I think this is handled by `curve25519-dalek` and usually the curve/group library implements something like this anyway, so I think this is technically a no-op for `frost` but is a requirement for the RFC that it is implemented _somewhere_

**Comment by dconnolly** [comment]
I think strictly satisfied by `curve25519-dalek` hash to scalar implementations

https://github.com/cfrg/draft-irtf-cfrg-frost/issues/49
