### ISSUE TITLE
Change batching to work with big-endian-encoded scalars

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost#141]
The current implementation assumes Field::serialize will return a little-endian array, which is not always true (e.g. P256).

One possibility is adding a new `serialize_little_endian` method to the `Field` trait and used that.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/frost/141?planning-poker) with Zenhub @conradoplg @dconnolly

**Comment by conradoplg** [comment]
> Should this be closed now that #142 is merged or is there more work in this?

There is more work, this was a bug found during that ticket that it's not obvious how to fix so I opened a ticket for it
