### ISSUE TITLE
Write security proof for Rerandomized FROST

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost#216]
We want to write a security proof for Rerandomized FROST that we can refer to in the ZIP.

Not sure about where to put it, creating this ticket here just to track the work.

**Comment by mpguerra** [comment]
I believe we have something already @chelseakomlo is there anything that we can link to in here? When are you comfortable in adding the same link to the ZIP?

**Comment by conradoplg** [comment]
Done! https://eprint.iacr.org/2024/436
