### ISSUE TITLE
Investigate broadcast channel implementation

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost#217]
For practical usage, users will need a broadcast channel (mostly for distributed key generation), but it seems there isn't a good implementation of that in Rust. Investigate more and create one if needed. We might split this ticket after we investigate.

**Comment by dconnolly** [comment]
Preliminary research indicates the simple echo broadcast protocol amongst peer to peer channels may suffice to start:
 
- all parties can talk to all parties via secure channels (maybe Noise pipes)
- announcer sends a message to all parties
- all parties who receive a message echo it to all parties, unless they are the original announcer
- end

This is my understanding of echo without finding a great written description of the protocol 👀 

This might be the canonical source? https://dl.acm.org/doi/10.1145/191177.191194

// @chelseakomlo

**Comment by conradoplg** [comment]
I read some papers and did a write-up in the "MPC Channels design" document.

> Preliminary research indicates the simple echo broadcast protocol amongst peer to peer channels may suffice to start:
> 
> * all parties can talk to all parties via secure channels (maybe Noise pipes)
> * announcer sends a message to all parties
> * all parties who receive a message echo it to all parties, unless they are the original announcer
> * end
> 
> This is my understanding of echo without finding a great written description of the protocol eyes

I think that's pretty much it, it's basically the "broadcast with abort" protocol from https://eprint.iacr.org/2002/040.pdf:

![image](https://user-images.githubusercontent.com/35766/216438398-8f822207-3cb5-4158-925e-67b5a73ea6fc.png)

**Comment by mpguerra** [comment]
How are we doing with this one? Can this be closed at the end of Sprint 3 (today)?

**Comment by conradoplg** [comment]
> How are we doing with this one? Can this be closed at the end of Sprint 3 (today)?

I think we'll decide tomorrow which scheme to implement, so we could close it then

**Comment by mpguerra** [comment]
I forget whether we made a decision last wednesday. We should wrap up and close this one though.
