### ISSUE TITLE
Fix batching for curves with order larger than 256 bits (i.e. Ed448)

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost#229]
Batching is currently hardcoded for 256-bit scalars. Make it generic so it works with any size.

Remember to restore the Ed448 batching tests that are currently disabled in `frost-ed448/tests/frost.rs`

(I swear we already had a ticket for this but I couldn't find it :thinking: )

**Comment by dconnolly** [comment]
This has been resolved by #347
