### ISSUE TITLE
Publish FROST documentation to frost.zfnd.org

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/frost#243]
## Motivation

We're getting closer to FROST being ready for production use and so we should publish the existing documentation somewhere that people can easily reference and browse. 

- [x] Use `mdbook` to create FROST book and link in any existing documents - #250 
- [x] Add a workflow to publish frost docs similar to how we do for zebra (https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/docs.yml)
- [x] Add DNS entries to point published frost docs to frost.zfnd.org

**Comment by mpguerra** [comment]
@gustavovalverde is the github workflow something you can do?

**Comment by gustavovalverde** [comment]
@mpguerra yes

**Comment by dconnolly** [comment]
We have Firebase static sites for the Zebra book and the self-hosted Zebra API docs; those are nicely behind our Google authentication, and once set up seem to require little maintenance

**Comment by mpguerra** [comment]
we still need to actually publish online

**Comment by dconnolly** [comment]
Done: frost.zfnd.org
