### ISSUE TITLE
Feature: remove signers or refresh shares with trusted dealer

### ISSUE THREAD

**Issue by natalieesk** [ZcashFoundation/frost#245]
## Motivation
There may be situations where you may want to _remove_ signers. 

## Design
To do this you would need to perform a resharing protocol and leave out the relevant participant.

This is done by basically redoing the trusted dealer generation with a "zero" secret, and adding the new shares to the old ones, while keeping only the participants that are wanted

## References
<add here>

**Comment by chelseakomlo** [comment]
I changed this issue to "remove signers or refresh shares" since the technique is the same.

**Comment by chelseakomlo** [comment]
Completed

**Comment by mpguerra** [comment]
@natalieesk can you please split this one up and we turn it into a tracking issue instead
