### ISSUE TITLE
Publish FROST API reference docs to doc.frost.zfnd.org 

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/frost#251]
## Motivation

We want to publish the FROST API reference documentation (generated with `cargo doc`) to doc.frost.zfnd.org, similar to what we do for Zebra.

### Related Issues

#243 deals with the user facing documentation (generated with `mdbook`) to be published to frost.zfnd.org

**Comment by dconnolly** [comment]
Closing: I don't think we should publish our rustdocs to a custom domain as we have done as zebra has been developed, they are published on https://docs.rs/frost-core/latest/frost_core/ etc; we should link to those from our book / README's
