### ISSUE TITLE
Ensure serialization/deserialization is up to date with spec

### ISSUE THREAD

**Issue by chelseakomlo** [ZcashFoundation/frost#27]
Especially the test vectors right now

**Comment by ftm1000** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/frost/27?planning-poker) with ZenHub @dconnolly

**Comment by chelseakomlo** [comment]
Waiting to finish this until the spec is ready for wide review

**Comment by dconnolly** [comment]
This may be basically defunct as the wire formats are getting removed from the spec per IETF CFRG feedback :/
