### ISSUE TITLE
is DKG mode for Key Gen process for Secpk2561 scheme works?

### ISSUE THREAD

**Issue by ThantZin-develope** [ZcashFoundation/frost#293]
is DKG mode avaiable now for keygen process of Secpk256k1 scheme? According to the implementaion of dkg.rs of frost-secpk256k1 a participant must broadcast the publicPackage through an authenticated channel. So Can I use the rabbitMQ for that? If yes, it can only be send the bytes data yet publicPackage struct of each round is not parseable sturct into bytes.

**Comment by conradoplg** [comment]
We're working on improving documentation to make these things clearer, but in the meantime...

> is DKG mode avaiable now for keygen process of Secpk256k1 scheme?

Yes, DKG is available for all ciphersuites.

> According to the implementaion of dkg.rs of frost-secpk256k1 a participant must broadcast the publicPackage through an authenticated channel. So Can I use the rabbitMQ for that?

I'm not familiar with rabbitMQ but in theory you can use it as long channels are authenticated (e.g. each peer knows who they're talking with, and attackers can't modify the messages being sent). rabbitMQ seems to [support TLS](https://www.rabbitmq.com/ssl.html) which could address that, but you would need to make sure by consulting someone more familiar with it.

> If yes, it can only be send the bytes data yet publicPackage struct of each round is not parseable sturct into bytes.

Encoding is up to the caller. You can serialize each field of the struct, encode them in any way you want, then decode/deserialized and rebuild the struct. We are planning to make this easier for library users.

**Comment by dconnolly** [comment]
> broadcast

rabbitMQ does not implement a _cryptographic broadcast channel_, which is what is meant by the term 'broadcast' in our rustdocs. I know this is not clear from our docs yet, which we intend to improve.

**Comment by ThantZin-develope** [comment]
Which channel protocol is prefered to use?

**Comment by conradoplg** [comment]
We added some guidance in the [docs](https://frost.zfnd.org/terminology.html#broadcast-channel). I know it's not super specific but surprisingly this is a problem for which there is no obvious solution. We're planning on working on a library to help doing this, however. I'm closing this for now but let us know if you have any questions.
