### ISSUE TITLE
Think about validating inputs in keygen_with_dealer and not just in generate_secret_polynomial

### ISSUE THREAD

**Issue by natalieesk** [ZcashFoundation/frost#327]
Currently we handle validation of `min_signers` and `max_signers` in `generate_secret_polynomial`. When calling `keygen_with_dealer` we accept these inputs but perform no validation on them until `generate_secret_polynomial` is called. `generate_secret_polynomial` is public and so if it's directly accessible we probably would want to validate the inputs in that function however. We should consider how best to handle validation in this instance as we would reduce computation effort by performing those validations up front.

**Comment by conradoplg** [comment]
Done in https://github.com/ZcashFoundation/frost/pull/453 after the audit found an issue related to this (good job anticipating it :laughing: )
