### ISSUE TITLE
structs to send over the wire should implement Deserialize + Serialize

### ISSUE THREAD

**Issue by dvc94ch** [ZcashFoundation/frost#336]
this should include at least these structs:
- dkg::round1::Package
- dkg::round2::Package
- SigningCommitments
- SignatureShare

**Comment by NoorahSmith** [comment]
Any workaround for sending these packages over p2p? 

Will  custom implementation  tobytes() for the structs mentioned above and the serde or bincode work ?

**Comment by conradoplg** [comment]
Done in https://github.com/ZcashFoundation/frost/pull/398
