### ISSUE TITLE
A trusted dealer should be able to accept a secret

### ISSUE THREAD

**Issue by natalieesk** [ZcashFoundation/frost#340]
The existing `keygen_with_dealer` generates the secret to be shared amongst signers. As per the spec, a dealer should also be able to accept a `secret_key` as input.

https://github.com/ZcashFoundation/frost/blob/main/frost-core/src/frost/keys.rs#L325

The inputs should be:
  - secret_key, a group secret, a Scalar, that MUST be derived from at least Ns
bytes of entropy.
  - MAX_PARTICIPANTS, the number of shares to generate, an integer.
  - MIN_PARTICIPANTS, the threshold of the secret sharing scheme, an integer.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/frost/340?planning-poker) with Zenhub @conradoplg @dconnolly @natalieesk

**Comment by mpguerra** [comment]
> Closed as completed in #314

technically it's not completed yet!
