### ISSUE TITLE
Document structure of serialized output in Frost book

### ISSUE THREAD

**Issue by natalieesk** [ZcashFoundation/frost#342]
### Context

When sharing commitments, shares etc. we need a consistent format for serialisation and deserialisation. This is should be the same when using broadcast channels or peer-to-peer channels.

### Acceptance Criteria

An addition to the dev section of the Frost book detailing structure

### Notes

Look at the data structures in zebra for inspiration on serialisation and deserialisation

**Comment by conradoplg** [comment]
This likely depends on #343

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/frost/342?planning-poker) with Zenhub @conradoplg @dconnolly @natalieesk

**Comment by dconnolly** [comment]
I think this will build on RFC 1 in the current book, but will require significant reworking/updating  as that spec was written before the FROST IRTF specification began, and doing a quick glance indicates divergance, beginning with the lack of ciphersuite encoding (as the first msg rfc was hard-coded to redjubjub)

**Comment by mpguerra** [comment]
closed by #511
