### ISSUE TITLE
Support serde

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost#343]
Requirements/design:

- Make it optional, behind a feature flag
- Include a ciphersuite ID when serializing and validate it when deserializing, to prevent deserializing a struct from one ciphersuite as a struct of another ciphersuite
- Do we need some versioning mechanism?

**Comment by dconnolly** [comment]
We might want to make use of `serdect` to implement for our secret types in constant time:
- `SigningKey`
- `Nonce`
- `Scalar`
- `SharedSecret`
- `SigningShare`
- `SecretShare`
- ?
