### ISSUE TITLE
Code samples in FROST book do not compile in playground

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/frost#350]
The code snippet for `frost-ed25519` in the FROST book (https://frost.zfnd.org/user/frost-ed25519.html) fails to compile and run.
![Screenshot 2023-05-17 at 16 57 16](https://github.com/ZcashFoundation/frost/assets/1311133/d9646b29-15fc-4200-b093-426c74a372ed)
This also happens with other code snippets in the FROST book

**Comment by conradoplg** [comment]
It seems playground doesn't support external crates (other than the top 100 crates) so it seems we'll need to disable it instead https://play.rust-lang.org/help#features-crates

**Comment by conradoplg** [comment]
We can close this, the existing snippets had playground disabled and those old snippets are not included in the book anymore.
