### ISSUE TITLE
Implement split() in demo so a trusted dealer can accept a secret

### ISSUE THREAD

**Issue by natalieesk** [ZcashFoundation/frost#362]
## Context
There has been a new function, split(), introduced in frost v0.3.0 that splits a secret key. This should be used in the demo to provide that functionality for a trusted dealer to accept that as input.

## Implementation
This should not impact the current trusted dealer flow which only accepts values for min and max signers.

The demo should ask for a secret and if a secret _is not_ supplied then it will take the current path of just using a config with min and max signers. If a secret _is_ supplied then that needs to be validated and a new config should be created and a new function which uses the split() function should be called.

## Error handling
If a secret is invalid, an error should be thrown with a useful message. The gen_with_dealer() function **must not** be called.

**Comment by conradoplg** [comment]
Closed by https://github.com/ZcashFoundation/frost-zcash-demo/pull/8
