### ISSUE TITLE
feature: Share redistribution - allow t signers to add new members and repair a user share

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/frost#41]
## Motivation

We want to be able to:
- Repair a user share (recompute it if it's lost)
- Add new signers - Just "recover" the share of the new user (e.g. using its identifier)

## Design

- Implement the Enrolment scheme from https://eprint.iacr.org/2017/1155.pdf
(or the Reduced Enrolment scheme; evaluate which one is better)
- Like the rest of the FROST implementation, communication is up to the caller, so we just want to provide functions to repair and add signers
- Write a test, e.g. simulating the communication using a HashMap

Preliminary design of functions to be implemented:

```

- helpers: Set of identifiers (signers that will help recover)
- requester: The identifier of the signer that lost their share


# For every single helper i in helpers:

# i: the identifier of the signer helping
# helpers: as above
# share_i: i's secret share
# zeta_i: Lagrange coefficient (?)
# - Note: may be able to be computed inside the function, check
# Output: i_deltas: random values that sum up to zeta_i * share _i
compute_random_values(i, helpers, share_i, zeta_i) -> deltas_i

# Communication round:
# Helper i sends deltas_i[j] to helper j

# j: the identifier of the signer helping
# helpers: as above
# deltas_j: values received by j in the communication round
# Output: sigma_j
compute_sum_of_random_values(j, helpers, deltas_j) -> sigma_j

# Communication round
# Helper j sends sigma_j to signer r

# sigmas: all sigma_j received from each helper j
# Output: share_r: r's secret share
recover_share(sigmas) -> share_r
```

### Specifications

See https://github.com/chelseakomlo/talks/blob/master/2019-combinatorial-schemes/A_Survey_and_Refinement_of_Repairable_Threshold_Schemes.pdf

**Comment by ppoliani** [comment]
This would be a super awesome feature to be honest.

**Comment by mpguerra** [comment]
Hey @natalieesk I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/engineering-team-5fb24d9264a3e8000e666a9e/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by mpguerra** [comment]
@conradoplg can you work together with @natalieesk to fill in the details for this issue?

**Comment by mpguerra** [comment]
and add in an estimate 🙏

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/frost/41?planning-poker) with Zenhub @conradoplg @natalieesk
