### ISSUE TITLE
BTC Taproot (BIP340) compatible

### ISSUE THREAD

**Issue by lucky1024** [ZcashFoundation/frost#439]
Hi experts,

Are there any plans to make it BTC Taproot (BIP340) compatible?

**Comment by lucky1024** [comment]
> Not currently, but it shouldn't be too hard. If anyone is wants to give it a shot, I sketched the changes needed here [cfrg/draft-irtf-cfrg-frost@master...conradoplg:draft-irtf-cfrg-frost:taproot](https://github.com/cfrg/draft-irtf-cfrg-frost/compare/master...conradoplg:draft-irtf-cfrg-frost:taproot) (but that's completely untested).
> 
> I'll leave this open to track it.

It seems sk_i also need be negated if group_public_key y coordinate is odd.

<img width="539" alt="image" src="https://github.com/ZcashFoundation/frost/assets/45564985/ccf4227a-d36b-4e20-bc07-5192c83502c3">

Here is an implentation https://github.com/jesseposner/FROST-BIP340/blob/main/frost.py

**Comment by zebra-lucky** [comment]
I've added some testing implementation.

https://github.com/zebra-lucky/frost/commit/cb22cf5c1b64f05a7d2fa125045b686fb39054a1

Possibly after review it can be added in some way to the upstream code.

**Comment by conradoplg** [comment]
> I've added some testing implementation.
> 
> [zebra-lucky@cb22cf5](https://github.com/zebra-lucky/frost/commit/cb22cf5c1b64f05a7d2fa125045b686fb39054a1)
> 
> Possibly after review it can be added in some way to the upstream code.

Cool! I haven't reviewed it carefully but it seems about right.

If you decide to submit a PR, note that we would prefer to create a separate ciphersuite for it, and not changing the existing secp256k1 one. (this entails basically having a separate folder for it, e.g, frost-taproot or frost-bip340 and changing the Ciphersuite name/ID accordingly).

Alternatively you can keep it as separate crate, and just submit a PR for frost-core.

**Comment by zebra-lucky** [comment]
Ок, I'll look to create a separate crarte/ciphersuite.

**Comment by zebra-lucky** [comment]
I've try add a PR https://github.com/ZcashFoundation/frost/pull/584

Some more changes are probably needed.
