### ISSUE TITLE
Remove frost module

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost#490]
In frost-core we currently have

- crate: non-FROST types for signing and verifying
- crate::frost: FROST types
- crate::frost::{keys, round1, round2}: the rest

However ciphersuite crates have

- crate: non-FROST types for signing and verifying, and FROST types
- crate::{keys, round1, round2}: the rest

Change frost-core to follow the ciphersuite crates, merging `crate::frost` into `crate::` and removing `crate::frost` and move child modules up accordingly.

This is a significant (though simple) refactoring so we should do this after all open PRs are merged

**Comment by hdevalence** [comment]
Would this be just moving code around, or changing what's exposed in the public API?

We're working on a FROST implementation here https://github.com/penumbra-zone/decaf377-rdsa/pull/18 and would be happy to track any refactors there, just wondering if we should expect code we're currently using to disappear.
