### ISSUE TITLE
Rename fields to match types

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost#495]
We did a bunch of type renamings but forgot to rename fields that used them.

For example, `signer_pubkeys` which is a map of `VerifyingShare`s so it should probably be named `verifying_shares`; `group_public` which is a `VerifyingKey` and should be named `verifying_key` and so on.

Rename all fields to match the types where that makes sense.

This would be a big refactoring so we should do it after all audit issues are merged.

**Comment by natalieesk** [comment]
Types:

- [ ] VerifyingShare
- [ ] VerifyingKey
- [ ] SigningShare
