### ISSUE TITLE
`SigningKey::{from_scalar, to_scalar}` methods are inconveniently hidden

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/frost#497]
These methods are gated by an `internals` feature:
```rust
    /// Creates a SigningKey from a scalar.
    #[cfg(feature = "internals")]
    pub fn from_scalar(
        scalar: <<<C as Ciphersuite>::Group as Group>::Field as Field>::Scalar,
    ) -> Self {
        Self { scalar }
    }

    /// Return the underlying scalar.
    #[cfg(feature = "internals")]
    pub fn to_scalar(self) -> <<<C as Ciphersuite>::Group as Group>::Field as Field>::Scalar {
        self.scalar
    }
```
We want to use these methods to bridge between our existing key types and the FROST types; it'd be convenient if the methods were exposed by default.

I don't think there's any meaningful increase in encapsulation, since the secret is already exposed via the serialization methods.

**Comment by dconnolly** [comment]
@hdevalence would this be convenient when implementing a `Ciphersuite`, or when using an implemented ciphersuite implementation?
