### ISSUE TITLE
high level state machine

### ISSUE THREAD

**Issue by dvc94ch** [ZcashFoundation/frost#501]
currently it requires quite a bit of logic to hook the crypto up into a state machine. we've implemented roast/dkg/recovery helper/recovery state machines and a root level state machine.

The root level state machine api looks something like this:
```
new(peer, members, threshold) -> Self
recover(peer, members, threshold, commitment, public_key_package) -> Self
sign(id, data)
on_message(peer, message)
next_action() -> Option<Action>
```

This is something that is probably useful for many consumers of frost and would probably benefit from some additional eyes. Should I open a preliminary PR next week to discuss if this is something that is in scope for this repo?

**Comment by conradoplg** [comment]
Could you describe this API in a bit more detail? I can't understand how it fits with FROST, for example where are the Round 1 commitments? Also the Coordinator and participants would have different state machines, no?

Also this library doesn't handle communication, so the API wouldn't be able to encapsulate sending and receiving messages (not sure if the proposed API does that) unless some callback mechanism is used.

**Comment by dvc94ch** [comment]
> for example where are the Round 1 commitments

That's internal to the state machine. `on_message` and `next_action` abstract this and for example prevent nonce reuse or other kinds of programmer errors.

> Also this library doesn't handle communication, so the API wouldn't be able to encapsulate sending and receiving messages (not sure if the proposed API does that) unless some callback mechanism is used.

Sending a message would be an action of the state machine, received messages are added to the state machine by calling on_message. So this is completely decoupled from any kind of io, as it should be.

> Also the Coordinator and participants would have different state machines, no?

Are you familiar with ROAST? It specifies a coordinator and a signer state machine, we implement both. And we determine which nodes need to run a coordinator state machine and which don't. since we need t nodes for producing a signature we can tolerate n - t failures. so if n - t + 1 nodes run a coordinator state machine at least one node in the threshold will run a coordinator.

Will open a PR to clarify how it works and if it's generic enough. At least the crypto will need to be generalized as it just uses our `frost-evm` crate currently, before it can be adapted for this repo. It's still under heavy development so will probably be towards the end of the week until I open a PR.
