### ISSUE TITLE
Enforce that THRESHOLD and NUM_SIGNERS are never greater than p

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/frost#56]
https://github.com/cfrg/draft-irtf-cfrg-frost/pull/165/files

**Comment by conradoplg** [comment]
Is this still needed since both must be smaller or equal to `MAX_SIGNERS`, and that must be smaller than `2^16-1`? i.e. do we need to worry about toy implementations with very small primes?

**Comment by dconnolly** [comment]
Will never happen because can't be larger than 2^16
