### ISSUE TITLE
Use RustCrypto's `MockCurve` inside `frost-core` tests when `frost-ristretto255` is impl'd using `frost-core` and running its own test vectors

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/frost#58]
There is duplicate code inside `frost-core` between it and `frost-ristretto`; we can retain testing for `frost-core` by using the `MockCurve` type provided by RustCrypto instead and remove the duplication.

**Comment by dconnolly** [comment]
I think this is now defunct per @conradoplg trying it out

**Comment by conradoplg** [comment]
For the record, MockCurve [does not implement the arithmetic](https://github.com/RustCrypto/traits/blob/147a4e8460433bdb4632c941df3d9306e6ce6099/elliptic-curve/src/dev.rs#L130) so it can't be used for this type of tests
