### ISSUE TITLE
Design phase 2 of adding communication to demo

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost#585]
In the first phase we added simple socket communication to the demo, with the coordinator acting as the server.

Design phase 2, which increments the previous phase somehow. This could involve, for example:

- Decoupling server from coordinator
- Integrating some other third-party library

**Comment by mpguerra** [comment]
I'll start a discussion on github with the 2 alternatives for this

**Comment by mpguerra** [comment]
I think we're done here
