### ISSUE TITLE
bug: invalid type: string \"FROST-secp256k1-SHA256-v1\", expected a borrowed string

### ISSUE THREAD

**Issue by mimoo** [ZcashFoundation/frost#588]
I'm getting the following error:

```
error while reading file: Error("invalid type: string \"FROST-secp256k1-SHA256-v1\", expected a borrowed string", line: 4, column: 46)
```

after serializing and deserializing a `frost::keys::KeyPackage` with json_serde.

**Comment by conradoplg** [comment]
Interesting. The fix seems correct but I can't come up with a test case that shows the issue. I'd like to add a test to exercise it. Can you share how are you serializing/deserializing it?

**Comment by mimoo** [comment]
are you using serde_json in your test? I just use `serde_json::{to_string, from_str}()`

**Comment by conradoplg** [comment]
> are you using serde_json in your test? I just use `serde_json::{to_string, from_str}()`

Yes. This test passes:

```
#[test]
fn check_key_package_serialization2() {
    let json = r#"{
        "header": {
          "version": 0,
          "ciphersuite": "FROST-secp256k1-SHA256-v1"
        },
        "identifier": "000000000000000000000000000000000000000000000000000000000000002a",
        "signing_share": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9d1c9e899ca306ad27fe1945de0242b81",
        "verifying_share": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
        "verifying_key": "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
        "min_signers": 2
      }"#;
    let key_package: KeyPackage = serde_json::from_str(json).unwrap();
    let json: String = serde_json::to_string(&key_package).unwrap();
    println!("{}", json);
    let _key_package: KeyPackage = serde_json::from_str(&json).unwrap();
}
```

I think it fails when it can't get a reference to the ciphersuite substring inside the JSON string, which usually happens if the string has some escape code, which isn't the case.
