### ISSUE TITLE
Rename `frost::keys::{Secret, Public}`to indicate signing participants' shares, not full keys.

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/frost#59]
These are the signing pariticipant's secret share and corresponding public key, as opposed to the "full signature" signing key and verifying key. We have another type called SecretShare that has more metadata, hence not being named such, but we probably should rename them for clarity. This is somewhat low priority while the frost-core API remains unstable (by SemVer standards).

**Comment by dconnolly** [comment]
Answer: yes, these are the signing pariticipant's secret share and corresponding public key, as opposed to the "full signature" signing key and verifying key. We have another type called `SecretShare` that has more metadata, hence not being named such, but we probably should rename them for clarity. This is somewhat low priority while the frost-core API remains unstable (by SemVer standards).

**Comment by conradoplg** [comment]
Any ideas for the new names?

`Secret` could become `SecretShareValue` but I'm not sure about `Public`, since the values are not strictly shares of the group public key in the same way. Maybe `PublicVerificationShare` following the paper? Though the spec does call them public keys...
