### ISSUE TITLE
`frost-core`: update for spec version 5 

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/frost#60]
v5: https://www.ietf.org/archive/id/draft-irtf-cfrg-frost-05.html

From the spec changelog:
- [ ] Update test vectors to include version string 
  - [ ] Rename THRESHOLD_LIMIT to MIN_SIGNERS (this will be automatically done when updating test vectors; the code doesn't read that field so no further changes are needed)
- [ ] Use non-contiguous signers for the test vectors 
- [ ] Add a function to generate nonces (#182)
~- [ ] Add MUST that all participants have the same view of VSS commitment~
- [ ] Use THRESHOLD_LIMIT instead of t and MAX_SIGNERS instead of n
~- [x] Remove wire format section (#156)~
- [ ] Update group commitment derivation to have a single scalarmul
- [ ] Use RandomNonzeroScalar for single-party Schnorr example (this should not be needed if we use `nonce_generate` instead)

**Comment by conradoplg** [comment]
Done in https://github.com/ZcashFoundation/frost/pull/89
