### ISSUE TITLE
Reject identity in Group::serialize

### ISSUE THREAD

**Issue by doutv** [ZcashFoundation/frost#667]
In current RFC document 3.1, page 10: 
> SerializeElement(A): Maps an Element A to a canonical byte array
buf of fixed length Ne. This function raises an error if A is the
identity element of the group.

Serialize a Group identity element should raise error.

Related PR:
https://github.com/cfrg/draft-irtf-cfrg-frost/pull/306
https://github.com/ZcashFoundation/frost/pull/145

**Comment by conradoplg** [comment]
Thank you for reporting this! It was good timing since the next release will be an API-breaking one.
