### ISSUE TITLE
Add Ed25519 support

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost#70]
We want to support all curves defined in the spec.

**Comment by conradoplg** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/frost/70?planning-poker) with ZenHub @dconnolly

**Comment by dconnolly** [comment]
I rated this a 5 because this is the ciphersuite that we are trying to get interop with https://datatracker.ietf.org/doc/html/rfc8032 and has caused us the most friction out of all the ciphersuites so far
