### ISSUE TITLE
Add Ed448 support

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/frost#71]
We want to support all curves defined in the spec.

**Comment by kayabaNerve** [comment]
Unfortunately, there's not really good Rust libraries for Ed448 (or in general). There is [ed448-goldilocks](https://github.com/crate-crypto/Ed448-Goldilocks/issues), which seems to be very expansive at embracing Ed448 and the associated items, yet may have some integrity issues (there's an open issue for one of the functionalities offered, though I'd assume as needed for FROST it's fine).

I wrote up an [Ed448 implementation](https://github.com/serai-dex/serai/tree/ed448/crypto/ed448) against ff/group which is... pretty bad. Poor performance with a few unimplemented functions. It should be complete in what it does offer though, is constant time, is no_std itself (probably needs a PR to manage its dependencies properly for a nostd deployment however), and also rejects torsion and non-canonical values (so designed to be usable without quirks and gotchas, which was my personal concern with goldilocks).

While I'm sure y'all could write an Ed448 library pretty quickly, it's not really the most difficult bit of code, I wanted to offer the heads up in case you wanted to use/fork the ff/group based offering.

**Comment by conradoplg** [comment]
@mpguerra updated!
