### ISSUE TITLE
Add functions to validate signature shares under "internals" feature

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [ZcashFoundation/frost#726]
I'm trying to implement [ROAST: Robust Asynchronous Schnorr Threshold Signatures](https://eprint.iacr.org/2022/550.pdf) using `frost-core` and I see that it has [`SignatureShare::verify()`](https://docs.rs/frost-secp256k1/latest/frost_secp256k1/round2/type.SignatureShare.html#method.verify) API, but it seems to be not enough to implement ROAST.

The thing is that ROAST collects signature shares and validates each of them instead of collecting everything at once and then accusing some participant of not following the protocol (like [`frost::aggregate()`](https://docs.rs/frost-secp256k1/latest/frost_secp256k1/fn.aggregate.html) does).

It would also be nice to move the function of checking one signature share out of `detect_cheater` and make it internal.
https://github.com/ZcashFoundation/frost/blob/dcf17732f791cd5c69aeed5bb4ff60d019a57ee8/frost-core/src/lib.rs#L651-L658

**Comment by conradoplg** [comment]
Thanks for reporting this. Coincidentally this was just reported in #724 so I'm closing this. I've just opened a [PR](https://github.com/ZcashFoundation/frost/pull/727) for it though, could you double check if  that addresses your use case?
