### ISSUE TITLE
Consider enabling the `precomputed-tables` feature for `k256`

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [ZcashFoundation/frost#738]
I haven't tested it, but it will probably increase performance (especially with a large number of DKG participants)

https://github.com/ZcashFoundation/frost/blob/dcf17732f791cd5c69aeed5bb4ff60d019a57ee8/frost-secp256k1/Cargo.toml#L28
https://docs.rs/crate/k256/latest/features

**Comment by StackOverflowExcept1on** [comment]
I benchmarked and it didn't lead to any improvement.

**Comment by conradoplg** [comment]
Thanks for looking into it! It seems that only speeds up multiplications with the generator point, and in FROST they only happen in commit generation if I remember correctly, which is not performance-critical.
