### ISSUE TITLE
Port fresh keygen test from `frost-core` to `frost-ristretto` and other dependent crates

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/frost#74]
Right now this test only exists in `frost-core`, it should also have a version in each dependent library, and possibly be a doctest in the README of each top level crate.

https://github.com/ZcashFoundation/frost/blob/a0bf3c57f2bed1c8559153afdd08845d01a0168d/frost-core/tests/frost.rs#L11

**Comment by conradoplg** [comment]
This was made generic in #105

**Comment by conradoplg** [comment]
Done in #105
