### ISSUE TITLE
Start rerandomized repo

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/frost#81]
- [ ] Create `rerandomized` repo
- Can inherit the history of the redjubjub repo
- [ ] Create `rerandomized-frost` crate
- [ ] Pull in `frost-core`
- [ ] Create new traits that impl the rerandomization of keys and handles aggregation with number signers and alpha shard
  - There's some design work to be done here to figure out where exactly the alpha shard is a parameter and where it's not, in the API that exists

**Comment by conradoplg** [comment]
This is blocked on deciding if we're happy with a `randomized_frost.rs` in `reddsa` (see https://github.com/ZcashFoundation/reddsa/pull/26 ) or if we do want a separate repo/crate. I'm fine either way.

**Comment by dconnolly** [comment]
We're putting all the frost crates in the one repo
