### ISSUE TITLE
Encoding of Scalars: Endianness

### ISSUE THREAD

**Issue by chelseakomlo** [ZcashFoundation/frost#90]
When converting from an index to a Scalar and vice-versa, the conversion assumes the Scalar is encoded in little-endian, but that's not true for P-256 (i.e. it writes the index as two little endian bytes at the start of a buffer, and deserializes it). However, the tests are passing...

Two reasons:
1. The conversions have the same bug in both sides, so it's consistent. But it's encoding the index 1 into 2^248, 2 into 2*2^248, and so on
2. But why it passed test vectors? Because derive_lagrange_coefficient cancels any common factors since it's bunch of scalars multiplied, divided by another bunch of scalars multipled, so it cancels out the 2^248 common factor.

...but writing this, I just noticed it may break for indices >= 256, since it will encode e.g. 256 as 2^240?

**Comment by chelseakomlo** [comment]
Waiting on chat with Chris Wood

**Comment by dconnolly** [comment]
I think we have resolved this in the spec
